services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "3306:3306"
        
  backend:
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    build:
      dockerfile: docker/backend.Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"

  periodic_backup:
    environment:
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    build: 
      dockerfile: docker/backup.Dockerfile
    depends_on:
      - db
    volumes:
      - ./db_backup:/tmp/db_backup