services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
        
  frontend:    
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    build:
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"    

  backend:
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DOCKER_RUNNING: 1
    build:
      dockerfile: docker/backend.Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      db:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"

  periodic_backup:
    environment:
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    build: 
      dockerfile: ./docker/backup.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db_backup:/tmp/db_backup