services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "3306:3306"
        
  frontend:    
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    build:
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"    


  backend:
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    build:
      dockerfile: docker/backend.Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"

  periodic_backup:
    environment:
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    build: 
      dockerfile: docker/backup.Dockerfile
    depends_on:
      - db
    volumes:
      - ./db_backup:/tmp/db_backup