services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
